[package]
name = "fshc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive", "help", "color"] }
procfs = "0.15"
sysexits = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
